"""empty message

Revision ID: 2bce2ef34027
Revises: c7a968ecaf33
Create Date: 2025-09-20 18:14:55.628838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bce2ef34027'
down_revision: Union[str, Sequence[str], None] = 'c7a968ecaf33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', sa.String(), nullable=False, server_default="active"))
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), nullable=False))
    op.drop_column('users', 'status')
    # ### end Alembic commands ###
